[project]
name = "mindcare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "ruff>=0.11.7",
    "uvicorn>=0.34.2",
]
